# Generated by Django 4.1 on 2022-09-08 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0003_remove_game_mode_game_moves'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pending_Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_inviting', models.CharField(choices=[('white', 'white'), ('black', 'black')], max_length=5)),
                ('time', models.IntegerField()),
                ('increment', models.IntegerField()),
                ('invited', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited', to='players.profile')),
                ('inviting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inviting', to='players.profile')),
            ],
        ),
    ]
