# Generated by Django 4.1.1 on 2022-09-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_game',
            name='invited',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='pending_game',
            name='inviting',
            field=models.CharField(default='', max_length=30),
        ),
    ]
