# Generated by Django 4.1 on 2022-09-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_remove_game_mode_game_moves'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='draws',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='victories',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
