# Generated by Django 4.1.1 on 2022-09-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_profile_draws_profile_losses_profile_victories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
