# Generated by Django 4.1.1 on 2022-09-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_alter_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='winner',
        ),
        migrations.AddField(
            model_name='game',
            name='outcome',
            field=models.CharField(default='', max_length=8),
        ),
    ]
